version: '3.8'

services:
  ollama:
    build: ./models
    ports:
      - "11435:11434"  # Map local port 11436 to container port 11434
    volumes:
      - ./ollama/ollama:/root/.ollama  # Persist Ollama models
    container_name: ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
    command: ["serve"]

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Backend communicates with Ollama via Docker network
      - PYTHONPATH=/app
    depends_on:
      - ollama
    volumes:
      - ./backend:/app
    networks:
      - ollama-docker

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000  # Frontend communicates with Backend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - ollama-docker

volumes:
  ollama_data:  # Volume for persisting Ollama models

networks:
  ollama-docker:
    external: false