data:
  input_dir: "./data/raw/clemson_faculty_docs"
  vector_db_path: "./data/processed/clemson_faculty_docs"

embeddings:
  model: "nomic-embed-text"
  chunk_size: 1000
  chunk_overlap: 300
  base_url: 'http://localhost:11434'
  # base_url: 'http://ollama:11434'

llm:
  model: "llama3.2:3b"
  base_url: 'http://localhost:11434'
  # base_url: 'http://ollama:11434'

retrieval:
  vector_db: "faiss"
  top_k: 6
  search_type: "similarity"

deployment:
  type: 'local'
